name: Fetch YouTube Trending

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Allow manual run from GitHub

jobs:
  fetch-trending:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch script
      env:
        API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python fetch_youtube_data.py

    - name: Commit and push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add realtime_trending.csv
        git commit -m "🕒 Update trending data"
        git push
